using DataEngine.ReaderService.Services;
using DataEngine.TransactionService.Domain;
using DataEngine.TransactionService.Interfaces;
using Microsoft.Extensions.Logging;
using System.Data;
using System.Data.Common;

namespace DataEngine.TransactionService.Services;

/// <summary>
/// Operational transaction service executing complex, multi-level parent-child modifications inside an atomic scope.
/// </summary>
public sealed class TransactionService(
    DatabaseConnectionFactory connectionFactory,
    IFieldMapperRepository fieldMapperRepository,
    ILogger<TransactionService> logger) : ITransactionService
{
    private readonly DatabaseConnectionFactory _connectionFactory = connectionFactory ?? throw new ArgumentNullException(nameof(connectionFactory));
    private readonly IFieldMapperRepository _fieldMapperRepository = fieldMapperRepository ?? throw new ArgumentNullException(nameof(fieldMapperRepository));
    private readonly ILogger<TransactionService> _logger = logger ?? throw new ArgumentNullException(nameof(logger));

    /// <inheritdoc />
    public async Task<TransactionResult> TransactionAsync(TransactionRequest request, CancellationToken ct = default)
    {
        if (request == null || string.IsNullOrWhiteSpace(request.TransactionEntityName))
        {
            return new TransactionResult { Success = false, Message = "Invalid transaction payload validation targets." };
        }

        string transactionId = string.IsNullOrWhiteSpace(request.TransactionId)
            ? Guid.NewGuid().ToString()
            : request.TransactionId;

        await using DbConnection connection = await _connectionFactory.CreatePrimaryConnectionAsync(ct);
        await using DbTransaction transaction = await connection.BeginTransactionAsync(IsolationLevel.ReadCommitted, ct);

        try
        {
            _logger.LogInformation("Beginning execution sequence for TransactionId: {TxId} targeting {Table}", transactionId, request.TransactionEntityName);

            var mappersCache = new Dictionary<string, List<FieldMapper>>(StringComparer.Ordinal);

            var mainMappers = await GetMappersCachedAsync(request.TransactionEntityName, connection, mappersCache);
            string operationType = DetermineOperationType(request.ExtendedProperties, mainMappers);

            object mainRecordId;
            if (operationType == "Insert")
            {
                mainRecordId = await ProcessInsertAsync(request.TransactionEntityName, request.ExtendedProperties, mainMappers, request.UserId, connection, transaction, ct);
            }
            else
            {
                mainRecordId = await ProcessUpdateAsync(request.TransactionEntityName, request.ExtendedProperties, mainMappers, request.UserId, connection, transaction, ct);
            }

            if (request.RenProps != null && request.RenProps.Count > 0)
            {
                await ProcessChildRecordsAsync(request.RenProps, mainRecordId.ToString()!, connection, transaction, mappersCache, request.UserId, 1, ct);
            }

            if (request.DelProps != null && request.DelProps.Count > 0)
            {
                await ProcessDeleteOperationsAsync(request.DelProps, connection, transaction, ct);
            }

            await transaction.CommitAsync(ct);

            return new TransactionResult
            {
                Success = true,
                TransactionId = transactionId,
                Message = $"Transaction committed successfully. Node affected: {operationType}.",
                Data = new Dictionary<string, object> { { "RENGUID", mainRecordId } }
            };
        }
        catch (Exception ex)
        {
            await transaction.RollbackAsync(ct);
            _logger.LogError(ex, "FATAL TRANSMISSION CRASH: Rolling back execution scope. TxId: {TxId}", transactionId);
            return new TransactionResult { Success = false, TransactionId = transactionId, Message = $"Transaction rolled back: {ex.Message}" };
        }
    }

    private string DetermineOperationType(Dictionary<string, object> properties, List<FieldMapper> mappers)
    {
        var autoGenMapper = mappers.FirstOrDefault(m => m.Properties != null && m.Properties.Contains("AutoGenerated", StringComparison.OrdinalIgnoreCase));
        if (autoGenMapper != null && properties.TryGetValue(autoGenMapper.FieldName, out var val) && val != null && !string.IsNullOrWhiteSpace(val.ToString()) && val.ToString() != "0")
        {
            return "Update";
        }

        if (properties.TryGetValue("id", out var fallbackId) && fallbackId != null && !string.IsNullOrWhiteSpace(fallbackId.ToString()) && fallbackId.ToString() != Guid.Empty.ToString())
        {
            return "Update";
        }

        return "Insert";
    }

    private async Task<object> ProcessInsertAsync(string tableName, Dictionary<string, object> data, List<FieldMapper> mappers, string userId, DbConnection conn, DbTransaction tx, CancellationToken ct)
    {
        var activeMappers = mappers.Where(m => m.Properties == null || !m.Properties.Contains("AutoGenerated", StringComparison.OrdinalIgnoreCase)).ToList();

        var columns = new List<string>();
        var values = new List<string>();
        var commandParams = new Dictionary<string, object?>(StringComparer.Ordinal);

        foreach (var mapper in activeMappers)
        {
            columns.Add($"`{mapper.ColumnName}`");
            values.Add($"@{mapper.FieldName}");

            data.TryGetValue(mapper.FieldName, out var rawVal);
            commandParams[$"@{mapper.FieldName}"] = ResolveTokens(rawVal, mapper.DefaultValue, null);
        }

        columns.Add("`createdon`");
        values.Add("NOW()");

        columns.Add("`createdby`");
        values.Add("@sysUserId");
        commandParams["@sysUserId"] = userId;

        string sql = $"INSERT INTO `{tableName}` ({string.Join(", ", columns)}) VALUES ({string.Join(", ", values)}); SELECT LAST_INSERT_ID();";

        await using var command = conn.CreateCommand();
        command.CommandText = sql;
        command.Transaction = tx;

        foreach (var kp in commandParams)
        {
            var p = command.CreateParameter();
            p.ParameterName = kp.Key;
            p.Value = kp.Value ?? DBNull.Value;
            command.Parameters.Add(p);
        }

        var scalar = await command.ExecuteScalarAsync(ct);
        if (scalar == null || Convert.ToInt64(scalar) == 0)
        {
            if (commandParams.TryGetValue("@id", out var exactGuid) && exactGuid != null) return exactGuid;
            return Guid.NewGuid().ToString();
        }
        return scalar;
    }

    private async Task<object> ProcessUpdateAsync(string tableName, Dictionary<string, object> data, List<FieldMapper> mappers, string userId, DbConnection conn, DbTransaction tx, CancellationToken ct)
    {
        var idMapper = mappers.FirstOrDefault(m => m.Properties != null && m.Properties.Contains("AutoGenerated", StringComparison.OrdinalIgnoreCase));
        string idColumn = idMapper != null ? idMapper.ColumnName : "id";
        string idField = idMapper != null ? idMapper.FieldName : "id";

        if (!data.TryGetValue(idField, out var idValue) || idValue == null)
        {
            throw new InvalidOperationException($"Missing required primary key element lookup value fields inside targeting table framework update: {idField}");
        }

        var updateableMappers = mappers.Where(m => m.AllowUpdate && (m.Properties == null || !m.Properties.Contains("AutoGenerated", StringComparison.OrdinalIgnoreCase))).ToList();

        var assignmentLines = new List<string>();
        var commandParams = new Dictionary<string, object?>(StringComparer.Ordinal);

        foreach (var mapper in updateableMappers)
        {
            if (data.TryGetValue(mapper.FieldName, out var rawVal))
            {
                assignmentLines.Add($"`{mapper.ColumnName}` = @{mapper.FieldName}");
                commandParams[$"@{mapper.FieldName}"] = ResolveTokens(rawVal, null, null);
            }
        }

        assignmentLines.Add("`modifiedon` = NOW()");
        assignmentLines.Add("`modifiedby` = @sysUserId");
        commandParams["@sysUserId"] = userId;
        commandParams["@targetRecordId"] = idValue;

        string sql = $"UPDATE `{tableName}` SET {string.Join(", ", assignmentLines)} WHERE `{idColumn}` = @targetRecordId";

        await using var command = conn.CreateCommand();
        command.CommandText = sql;
        command.Transaction = tx;

        foreach (var kp in commandParams)
        {
            var p = command.CreateParameter();
            p.ParameterName = kp.Key;
            p.Value = kp.Value ?? DBNull.Value;
            command.Parameters.Add(p);
        }

        await command.ExecuteNonQueryAsync(ct);
        return idValue;
    }

    /// <summary>
    /// Processes recursive child rows up to a strict limit depth of 5 levels deep.
    /// </summary>
    private async Task ProcessChildRecordsAsync(
        Dictionary<string, List<Dictionary<string, object>>> renProps,
        string parentId,
        DbConnection conn,
        DbTransaction tx,
        Dictionary<string, List<FieldMapper>> mappersCache,
        string userId,
        int depth,
        CancellationToken ct)
    {
        if (depth > 5)
        {
            throw new InvalidOperationException("Execution truncated. Loop passed max recursion ceiling boundaries of 5 levels.");
        }

        foreach (var childBlock in renProps)
        {
            string childTable = childBlock.Key;
            var childMappers = await GetMappersCachedAsync(childTable, conn, mappersCache);

            foreach (var record in childBlock.Value)
            {
                string op = DetermineOperationType(record, childMappers);
                object childRecordId;

                foreach (var kvp in record.ToList())
                {
                    if (kvp.Value?.ToString() == "|RENGUID|")
                    {
                        record[kvp.Key] = parentId;
                    }
                }

                if (op == "Insert")
                {
                    childRecordId = await ProcessInsertAsync(childTable, record, childMappers, userId, conn, tx, ct);
                }
                else
                {
                    childRecordId = await ProcessUpdateAsync(childTable, record, childMappers, userId, conn, tx, ct);
                }

                if (record.TryGetValue("renProps", out var nestedObject) && nestedObject is Dictionary<string, List<Dictionary<string, object>>> deepRenProps)
                {
                    await ProcessChildRecordsAsync(deepRenProps, childRecordId.ToString()!, conn, tx, mappersCache, userId, depth + 1, ct);
                }
            }
        }
    }

    /// <summary>
    /// Executes cascading parameterized row deletions across specified table targets.
    /// </summary>
    private async Task ProcessDeleteOperationsAsync(
        Dictionary<string, List<Dictionary<string, object>>> delProps,
        DbConnection conn,
        DbTransaction tx,
        CancellationToken ct)
    {
        foreach (var delBlock in delProps)
        {
            string tableName = delBlock.Key;

            foreach (var record in delBlock.Value)
            {
                if (!record.TryGetValue("id", out var idVal) || idVal == null)
                {
                    throw new InvalidOperationException("Delete operations payloads must explicitly define target row 'id' values.");
                }

                string sql = $"DELETE FROM `{tableName}` WHERE `id` = @delId";

                await using var command = conn.CreateCommand();
                command.CommandText = sql;
                command.Transaction = tx;

                var p = command.CreateParameter();
                p.ParameterName = "@delId";
                p.Value = idVal;
                command.Parameters.Add(p);

                await command.ExecuteNonQueryAsync(ct);
            }
        }
    }

    /// <summary>
    /// Retrieves structural table mappings leveraging an internal request-scoped transaction cache.
    /// </summary>
    private async Task<List<FieldMapper>> GetMappersCachedAsync(
        string tableName,
        DbConnection conn,
        Dictionary<string, List<FieldMapper>> cache)
    {
        if (cache.TryGetValue(tableName, out var list))
        {
            return list;
        }

        var mappers = await _fieldMapperRepository.GetFieldMappersAsync(tableName, conn);
        cache[tableName] = mappers;
        return mappers;
    }

    /// <summary>
    /// Translates special framework evaluation string macros into strongly-typed runtime objects.
    /// </summary>
    private static object? ResolveTokens(object? value, string? defaultValue, string? parentId)
    {
        if (value == null)
        {
            if (defaultValue == "now" || defaultValue == "|Todaydate|") return DateTime.UtcNow;
            if (defaultValue == "|RENGUID|") return Guid.NewGuid().ToString();
            return null;
        }

        string str = value.ToString()!;
        if (str == "now" || str == "|Todaydate|") return DateTime.UtcNow;
        if (str == "|RENGUID|") return parentId ?? Guid.NewGuid().ToString();

        return value;
    }
}
