using System;
using System.Collections.Generic;
using Xunit;
using DataEngine.Core.Configuration;
using DataEngine.Core.Domain;
using DataEngine.Core.Resilience;
using DataEngine.Core.Security;
using DataEngine.Core.Services;
using DataEngine.Core.Utilities;
using Microsoft.Extensions.Caching.Memory;

namespace DataEngine.Core.Tests;

public class RefactoringTests
{
    [Theory]
    [InlineData("123", 123L)]
    [InlineData("0", 0L)]
    [InlineData("-45", -45L)]
    public void CoerceValue_Int_ParsesCorrectly(string input, long expected)
    {
        var result = DataTypeConverter.CoerceValue(input, "INT");
        Assert.Equal(expected, result);
    }

    [Theory]
    [InlineData("123.45", 123.45)]
    [InlineData("0.0", 0.0)]
    public void CoerceValue_Decimal_ParsesCorrectly(string input, double expected)
    {
        var result = DataTypeConverter.CoerceValue(input, "DECIMAL");
        Assert.Equal((decimal)expected, result);
    }

    [Theory]
    [InlineData("true", true)]
    [InlineData("1", true)]
    [InlineData("false", false)]
    [InlineData("0", false)]
    public void CoerceValue_Bool_ParsesCorrectly(string input, bool expected)
    {
        var result = DataTypeConverter.CoerceValue(input, "BOOL");
        Assert.Equal(expected, result);
    }

    [Fact]
    public void CoerceValue_Guid_ParsesCorrectly()
    {
        var target = Guid.NewGuid();
        var result = DataTypeConverter.CoerceValue(target.ToString(), "GUID");
        Assert.Equal(target, result);
    }

    [Fact]
    public void CoerceValue_DateTime_ParsesCorrectly()
    {
        var targetStr = "2026-07-07T12:00:00Z";
        var result = DataTypeConverter.CoerceValue(targetStr, "DATETIME");
        Assert.IsType<DateTime>(result);
        Assert.Equal(DateTime.Parse(targetStr).ToUniversalTime(), ((DateTime)result!).ToUniversalTime());
    }

    [Fact]
    public void CoerceValue_InvalidValue_ReturnsOriginal()
    {
        var result = DataTypeConverter.CoerceValue("not-a-number", "INT");
        Assert.Equal("not-a-number", result);
    }

    [Fact]
    public void GetPrimaryKeyMapper_ResolvesAutoGen()
    {
        var mappers = new List<FieldMapper>
        {
            new() { FieldName = "name", ColumnName = "name", DataType = "string" },
            new() { FieldName = "orderId", ColumnName = "order_id", DataType = "long", Properties = "AutoGenerated" }
        };

        var pk = TransactionService.GetPrimaryKeyMapper(mappers);
        Assert.Equal("orderId", pk.FieldName);
        Assert.Equal("order_id", pk.ColumnName);
    }

    [Fact]
    public void GetPrimaryKeyMapper_ResolvesPrimaryKey()
    {
        var mappers = new List<FieldMapper>
        {
            new() { FieldName = "code", ColumnName = "code_val", DataType = "string", Properties = "PrimaryKey" },
            new() { FieldName = "name", ColumnName = "name", DataType = "string" }
        };

        var pk = TransactionService.GetPrimaryKeyMapper(mappers);
        Assert.Equal("code", pk.FieldName);
        Assert.Equal("code_val", pk.ColumnName);
    }

    [Fact]
    public void GetPrimaryKeyMapper_ResolvesIdField()
    {
        var mappers = new List<FieldMapper>
        {
            new() { FieldName = "id", ColumnName = "record_id", DataType = "long" },
            new() { FieldName = "name", ColumnName = "name", DataType = "string" }
        };

        var pk = TransactionService.GetPrimaryKeyMapper(mappers);
        Assert.Equal("id", pk.FieldName);
        Assert.Equal("record_id", pk.ColumnName);
    }

    [Fact]
    public void GetPrimaryKeyMapper_ResolvesDefaultFallback()
    {
        var mappers = new List<FieldMapper>();
        var pk = TransactionService.GetPrimaryKeyMapper(mappers);
        Assert.Equal("id", pk.FieldName);
        Assert.Equal("id", pk.ColumnName);
    }

    [Fact]
    public void SqlErrorTranslator_ToSafeMessage_TranslatesGenericExceptions()
    {
        var ex = new InvalidOperationException("Fatal database error message or credentials leak");
        var safe = SqlErrorTranslator.ToSafeMessage(ex);
        Assert.Equal("An unexpected error occurred while processing the request.", safe);
    }

    [Fact]
    public void SqlErrorTranslator_ToSafeMessage_TranslatesOperationCanceled()
    {
        var ex = new OperationCanceledException();
        var safe = SqlErrorTranslator.ToSafeMessage(ex);
        Assert.Equal("The operation was cancelled or timed out.", safe);
    }

    [Fact]
    public async Task TableNameValidator_BlocksProhibitedSystemTables()
    {
        var opt = Microsoft.Extensions.Options.Options.Create(new DataEngineOptions
        {
            Connections = [ new DatabaseOptions { ConnectionString = "Server=localhost", FieldMappersTableName = "de_field_mappers" } ],
            Audit = new AuditOptions { ReadAuditTableName = "de_audit_read_log", WriteAuditTableName = "de_audit_write_log" }
        });

        var validator = new TableNameValidator(opt);

        await Assert.ThrowsAsync<UnauthorizedAccessException>(() => validator.EnsureAllowedAsync("de_query_definitions"));
        await Assert.ThrowsAsync<UnauthorizedAccessException>(() => validator.EnsureAllowedAsync("de_field_mappers"));
        await Assert.ThrowsAsync<UnauthorizedAccessException>(() => validator.EnsureAllowedAsync("de_audit_read_log"));
        await Assert.ThrowsAsync<UnauthorizedAccessException>(() => validator.EnsureAllowedAsync("de_audit_write_log"));
        
        var exception = await Record.ExceptionAsync(() => validator.EnsureAllowedAsync("users"));
        Assert.Null(exception);
    }

    [Fact]
    public async Task ValidationService_EvaluatesBusinessRules()
    {
        var options = Microsoft.Extensions.Options.Options.Create(new DataEngineOptions());
        var mockCache = new Microsoft.Extensions.Caching.Memory.MemoryCache(new Microsoft.Extensions.Caching.Memory.MemoryCacheOptions());
        var mockLogger = new Microsoft.Extensions.Logging.Abstractions.NullLogger<ValidationService>();

        var validationService = new ValidationService(options, null!, mockCache, mockLogger);

        var config = new ValidationConfiguration
        {
            Fields = [],
            BusinessRules = new List<BusinessRule>
            {
                new()
                {
                    RuleName = "CheckPriceRange",
                    Expression = "price >= cost",
                    ErrorMessage = "Price cannot be less than cost."
                },
                new()
                {
                    RuleName = "CheckStatus",
                    Expression = "status = 'Active'",
                    ErrorMessage = "Status must be Active."
                }
            }
        };

        mockCache.Set("validation::products", config, TimeSpan.FromMinutes(10));

        var passingData = new Dictionary<string, object>
        {
            { "price", 15.50m },
            { "cost", 10.00m },
            { "status", "Active" }
        };

        var resultPass = await validationService.ValidateAsync("products", passingData);
        Assert.True(resultPass.IsValid);

        var failingPriceData = new Dictionary<string, object>
        {
            { "price", 8.50m },
            { "cost", 10.00m },
            { "status", "Active" }
        };

        var resultFailPrice = await validationService.ValidateAsync("products", failingPriceData);
        Assert.False(resultFailPrice.IsValid);
        Assert.Single(resultFailPrice.Errors);
        Assert.Equal("Price cannot be less than cost.", resultFailPrice.Errors[0].ErrorMessage);

        var failingStatusData = new Dictionary<string, object>
        {
            { "price", 15.50m },
            { "cost", 10.00m },
            { "status", "Inactive" }
        };

        var resultFailStatus = await validationService.ValidateAsync("products", failingStatusData);
        Assert.False(resultFailStatus.IsValid);
        Assert.Single(resultFailStatus.Errors);
        Assert.Equal("Status must be Active.", resultFailStatus.Errors[0].ErrorMessage);
    }
}
