namespace DataEngine.TransactionService.Domain;

/// <summary>
/// Layout parameters detailing entity column types and data schema fallback constraints.
/// </summary>
public sealed record FieldMapper
{
    /// <summary>
    /// Property key name parsed from transaction payloads.
    /// </summary>
    public required string FieldName { get; init; }

    /// <summary>
    /// Real target column name inside the physical database instance schema.
    /// </summary>
    public required string ColumnName { get; init; }

    /// <summary>
    /// Type descriptor used to marshal payloads safely into native storage primitives.
    /// </summary>
    public required string DataType { get; init; }

    /// <summary>
    /// Default string token or configuration value applied on raw inserts.
    /// </summary>
    public string? DefaultValue { get; init; }

    /// <summary>
    /// Structural parameters indicating constraints such as AutoGenerated or Sequence definitions.
    /// </summary>
    public string? Properties { get; init; }

    /// <summary>
    /// Flag controlling visibility and operational states inside query builders.
    /// </summary>
    public bool IsActive { get; init; } = true;

    /// <summary>
    /// Restricts mutations on historical entries when updating records.
    /// </summary>
    public bool AllowUpdate { get; init; } = true;
}
