using DataEngine.ReaderService.Enums;
using Microsoft.Extensions.Logging;
using MySqlConnector;
using Oracle.ManagedDataAccess.Client;
using System.Data.Common;
using System.Text.Json;

namespace DataEngine.Core.Auditing;

public interface IAuditService
{
    Task RecordAsync(AuditEntry entry, DbConnection connection, DbTransaction transaction, CancellationToken ct);
}

public sealed record AuditEntry(
    string TransactionId,
    string Entity,
    string RecordId,
    AuditOperation Operation,
    object? BeforeData,
    object? AfterData,
    string UserId,
    string CorrelationId,
    string? IpAddress);

public sealed class AuditService(ILogger<AuditService> logger) : IAuditService
{
    private readonly ILogger<AuditService> _logger = logger ?? throw new ArgumentNullException(nameof(logger));

    public async Task RecordAsync(AuditEntry entry, DbConnection connection, DbTransaction transaction, CancellationToken ct)
    {
        ArgumentNullException.ThrowIfNull(entry);
        ArgumentNullException.ThrowIfNull(connection);
        ArgumentNullException.ThrowIfNull(transaction);

        await EnsureTableAsync(connection, transaction, ct);

        await using var cmd = connection.CreateCommand();
        cmd.Transaction = transaction;
        cmd.CommandText = GetInsertSql(connection);

        var prefix = GetParameterPrefix(connection);
        AddParam(cmd, $"{prefix}txId", entry.TransactionId);
        AddParam(cmd, $"{prefix}entity", entry.Entity);
        AddParam(cmd, $"{prefix}recordId", entry.RecordId);
        AddParam(cmd, $"{prefix}op", entry.Operation.ToString());
        AddParam(cmd, $"{prefix}before", entry.BeforeData is null ? DBNull.Value : JsonSerializer.Serialize(entry.BeforeData));
        AddParam(cmd, $"{prefix}after", entry.AfterData is null ? DBNull.Value : JsonSerializer.Serialize(entry.AfterData));
        AddParam(cmd, $"{prefix}userId", entry.UserId);
        AddParam(cmd, $"{prefix}correlationId", entry.CorrelationId);
        AddParam(cmd, $"{prefix}ip", (object?)entry.IpAddress ?? DBNull.Value);

        await cmd.ExecuteNonQueryAsync(ct);
    }

    private async Task EnsureTableAsync(DbConnection connection, DbTransaction transaction, CancellationToken ct)
    {
        try
        {
            await using var cmd = connection.CreateCommand();
            cmd.Transaction = transaction;

            if (connection is MySqlConnection)
            {
                cmd.CommandText = @"
                    CREATE TABLE IF NOT EXISTS de_audit_log (
                        audit_id BIGINT AUTO_INCREMENT PRIMARY KEY,
                        transaction_id VARCHAR(100) NOT NULL,
                        entity VARCHAR(128) NOT NULL,
                        record_id VARCHAR(100) NOT NULL,
                        operation VARCHAR(10) NOT NULL,
                        before_data JSON NULL,
                        after_data JSON NULL,
                        user_id VARCHAR(100) NOT NULL,
                        correlation_id VARCHAR(100) NOT NULL,
                        ip_address VARCHAR(45) NULL,
                        created_at DATETIME(6) NOT NULL,
                        INDEX ix_de_audit_entity_record (entity, record_id),
                        INDEX ix_de_audit_transaction (transaction_id),
                        INDEX ix_de_audit_created_at (created_at)
                    );";
            }
            else if (connection is OracleConnection)
            {
                cmd.CommandText = @"
                    BEGIN
                        EXECUTE IMMEDIATE 'CREATE TABLE de_audit_log (
                            audit_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            transaction_id VARCHAR2(100) NOT NULL,
                            entity VARCHAR2(128) NOT NULL,
                            record_id VARCHAR2(100) NOT NULL,
                            operation VARCHAR2(10) NOT NULL,
                            before_data CLOB NULL,
                            after_data CLOB NULL,
                            user_id VARCHAR2(100) NOT NULL,
                            correlation_id VARCHAR2(100) NOT NULL,
                            ip_address VARCHAR2(45) NULL,
                            created_at TIMESTAMP(6) NOT NULL)';
                    EXCEPTION
                        WHEN OTHERS THEN
                            IF SQLCODE != -955 THEN
                                RAISE;
                            END IF;
                    END;";
            }
            else
            {
                return;
            }

            await cmd.ExecuteNonQueryAsync(ct);
        }
        catch (Exception ex)
        {
            _logger.LogWarning(ex, "Audit table initialization skipped because the target database did not allow it. Auditing will continue with the current connection if the table already exists.");
        }
    }

    private static string GetInsertSql(DbConnection connection)
    {
        return connection switch
        {
            MySqlConnection => @"
                INSERT INTO de_audit_log
                    (transaction_id, entity, record_id, operation, before_data, after_data, user_id, correlation_id, ip_address, created_at)
                VALUES
                    (@txId, @entity, @recordId, @op, @before, @after, @userId, @correlationId, @ip, UTC_TIMESTAMP(6))",
            OracleConnection => @"
                INSERT INTO de_audit_log
                    (transaction_id, entity, record_id, operation, before_data, after_data, user_id, correlation_id, ip_address, created_at)
                VALUES
                    (:txId, :entity, :recordId, :op, :before, :after, :userId, :correlationId, :ip, SYSTIMESTAMP)",
            _ => @"
                INSERT INTO de_audit_log
                    (transaction_id, entity, record_id, operation, before_data, after_data, user_id, correlation_id, ip_address, created_at)
                VALUES
                    (@txId, @entity, @recordId, @op, @before, @after, @userId, @correlationId, @ip, CURRENT_TIMESTAMP)"
        };
    }

    private static string GetParameterPrefix(DbConnection connection)
    {
        return connection switch
        {
            OracleConnection => ":",
            _ => "@"
        };
    }

    private static void AddParam(DbCommand cmd, string name, object value)
    {
        var p = cmd.CreateParameter();
        p.ParameterName = name;
        p.Value = value;
        cmd.Parameters.Add(p);
    }
}
